name: EssentialsPE
main: EssentialsPE\Loader
version: 1.0.0 Beta2
api: 1.3.0
author: LegendOfMCPE Team
website: https://github.com/LegendOfMCPE/EssentialsPE

permissions:
    essentials:
        default: op
        description: "Allow to access to every EssentialsPE feature"
        children:
            essentials.ban.exempt:
                default: op
                description: "Prevent the player from being banned"
            essentials.colorchat:
                default: op
                description: "Allow to chat using colors!"
            essentials.afk:
                default: true
                description: "Toggle the AFK status"
                children:
                    essentials.afk.other:
                        default: op
                        description: "Change other's AFK status"
                    #essentials.afk.auto:
                    #    default: op
                    #    description: "Players with this permission will be set to AFK after a period of inaction"
                    essentials.afk.kickexempt:
                        default: op
                        description: "Exempt the user from being auto kicked for AFK"
            essentials.broadcast:
                default: op
                description: "Broadcast a message"
            essentials.burn:
                default: op
                description: "Set a player on fire"
            essentials.clearinventory:
                default: op
                description: "Clear a player inventory"
                children:
                    essentials.clearinventory.other:
                        default: op
                        description: "Clear other's inventory"
            essentials.compass:
                default: true
                description: "Display your current bearing direction"
            essentials.delwarp:
                default: op
                description: "Allow to delete a warp"
            essentials.essentials:
                default: op
                description: "See the current Essentials version"
                children:
                    essentials.essentials.reload:
                        default: op
                        description: "Let you reload the config file of EssentialsPE"
            essentials.extinguish:
                default: op
                description: "Extinguish a player"
                children:
                    essentials.extinguish.other:
                        default: op
                        description: "Extinguish other players"
            essentials.getpos:
                default: op
                description: "Get any player's position"
                children:
                    essentials.getpos.other:
                        default: op
                        description: "Get other player's position"
            essentials.god:
                default: op
                description: "Prevent a player to take any damage"
                children:
                    essentials.god.other:
                        default: op
                        description: "Prevent other players to take damage"
                    essentials.god.pvp:
                        default: op
                        description: "Let you attack other players while you're in god mode"
            essentials.heal:
                default: op
                description: "Heal yourself or other players"
                children:
                    essentials.heal.other:
                        default: op
                        description: "Heal other players"
            essentials.invsee:
                default: op
                description: "See other player's inventory"
                children:
                    essentials.invsee.modify:
                        default: op
                        description: "Let you add/remove items from other player's inventory"
                    essentials.invsee.preventmodify:
                        default: op
                        description: "Prevent other player's to modify your inventory"
            essentials.item:
                default: op
                description: "Gives yourself an item"
            essentials.itemdb:
                default: op
                description: "Let you see information attached to an item"
            essentials.itemspawn:
                default: op
                description: "Let you spawn any item using /item"
                children:
                    essentials.itemspawn.item-all:
                        default: op
                        description: "Let you spawn any item"
                    #essentials.itemspawn.exempt:
                    #    default: op
                    #    description: "Allow the spawning of blacklisted items"
            essentials.jump:
                default: op
                description: "Teleport you to the block you're looking at"
            essentials.kickall:
                default: op
                description: "Kick all the online players except the sender"
            essentials.more:
                default: op
                description: "Get a stack of the item you're holding"
            essentials.mute:
                default: op
                description: "Mute a player from the chat"
                chldren:
                    essentials.mute.exempt:
                        default: op
                        description: "Prevent a player from being muted"
            essentials.near:
                default: op
                description: "Let you search for near players"
                children:
                    essentials.near.other:
                        default: op
                        description: "Let you see who is near to another player"
            essentials.nick:
                default: op
                description: "Change your or others name"
                children:
                    essentials.nick.other:
                        default: op
                        description: "Change others name"
            essentials.oversizedstacks:
                default: op
                description: "Allow to get oversized stacks"
            essentials.powertool:
                default: op
                description: "Allow to toggle and use PowerTool"
                children:
                    essentials.powertool.append:
                        default: op
                        description: "Let you add multiple commands to the PowerTool"
            essentials.powertooltoggle:
                default: op
                description: "Allow to disable PowerTool from all the items (of a player)"
            essentials.pvp:
                default: true
                description: "Toggle PvP on/off"
            essentials.realname:
                default: op
                description: "See a player's realname"
            essentials.repair:
                default: op
                description: "Repair the item you're holding"
                children:
                    essentials.repair.all:
                        default: op
                        description: "Let you repair all the damaged tools/armors on your inventory"
                    essentials.repair.armor:
                        default: op
                        description: "Let your repair the equiped armor while using /repair all"
            essentials.seen:
                default: op
                description: "Check player's last online time"
            essentials.setspawn:
                default: op
                description: "Change your server's general spawn"
            essentials.setwarp:
                default: op
                description: "Allow to create a new warp"
            essentials.sign:
                default: op
                description: "Allow to manage special signs"
                children:
                    essentials.sign.break:
                        default: op
                        description: "Allow to remove special signs"
                        children:
                            essentials.sign.break.free:
                                default: op
                                description: "Allow to remove Free signs"
                            essentials.sign.break.gamemode:
                                default: op
                                description: "Allow to remove Gamemode signs"
                            essentials.sign.break.heal:
                                default: op
                                description: "Allow to remove heal signs"
                            essentials.sign.break.repair:
                                default: op
                                description: "Allow to remove repair signs"
                            essentials.sign.break.time:
                                default: op
                                description: "Allow to remove Time signs"
                            essentials.sign.break.teleport:
                                default: op
                                description: "Allow to remove Teleport signs"
                    essentials.sign.color:
                        default: op
                        description: "Allow to create colored signs"
                    essentials.sign.create:
                        default: op
                        description: "Allow to create special signs"
                        children:
                            essentials.sign.create.free:
                                default: op
                                description: "Allow to create Free signs"
                            essentials.sign.create.gamemode:
                                default: op
                                description: "Allow to create Gamemode signs"
                            essentials.sign.create.heal:
                                default: op
                                description: "Allow to create Heal signs"
                            essentials.sign.create.repair:
                                default: op
                                description: "Allow to create Repair signs"
                            essentials.sign.create.time:
                                default: op
                                description: "Allow to create Time signs"
                            essentials.sign.create.teleport:
                                default: op
                                description: "Allow to create Teleport signs"
                    essentials.sign.use:
                        default: op
                        description: "Allow to use special signs"
                        children:
                            essentials.sign.use.free:
                                default: op
                                description: "Allow to use Free signs"
                            essentials.sign.use.gamemode:
                                default: op
                                description: "Allow to use Gamemode signs"
                            essentials.sign.use.heal:
                                default: op
                                description: "Allow to use Heal signs"
                            essentials.sign.use.repair:
                                default: op
                                description: "Allow to use Repair signs"
                            essentials.sign.use.time:
                                default: op
                                description: "Allow to use Time signs"
                            essentials.sign.use.teleport:
                                default: op
                                description: "Allow to use Teleport signs"
            essentials.tempban:
                default: op
                description: "Temporary bans a player"
            essentials.top:
                default: op
                description: "Teleport to the highest block above you"
            essentials.unlimited:
                default: op
                description: "Allow the player to place unlimited blocks"
                children:
                    essentials.unlimited.other:
                        default: op
                        description: "Allow to enable unlimited placing of blocks to other players"
            essentials.vanish:
                default: op
                description: "Hide yourself or another player"
                children:
                    essentials.vanish.other:
                        default: op
                        description: "Hide other players"
                    essentials.vanish.pvp:
                        default: op
                        description: "Let you attack other players while you're vanished"
            essentials.warps:
                default: op
                description: "Access to /warp command"
                children:
                    essentials.warp.list:
                        default: op
                        description: "Get a list of available warps"
                    essentials.warp.other:
                        default: op
                        description: "Warp another player"
                    essentials.warps.*:
                        default: op
                        description: "Teleport to any warp"
                    essentials.warp.override.*:
                        default: op
                        description: "Allow to override any warp"
            essentials.world:
                default: op
                description: "Switch between world"
